sudo: false
language: ruby
rvm:
- 2.4.2
before_install: gem install bundler -v 1.16.0
deploy:
  provider: rubygems
  api_key:
    secure: ag2wJR+rCYqR++soriQoW8WSPy6wesi5Pl2wBGcEoXuDvCnvhLnK0KTzttatmsxHESoIQlpiuZXG1YyuMoOIZ5USIBtUPEmk1V8t+UiT76HlNqsE4veYyp2LzsBhXkd08Upk1MJF9p1/GyU7Q0jBIOtuXyEmYUz+FYOVRwt7V6/wbD4JbusEcd4WiADup0LmtbPgoCPBPjf/3wNIvBdVXAD691P55W7N95ZFk/yPL/9aYc/W8gmXRuW3p3MfpZaHqdXfrI/jfepOqvNR2kwEOeiZqCibUAvzW/YmUg45SpKP1Odqm3DCRdpSB/txYyetLGmcJpIOq5wPPubQc36wzT9sSIhkzwZnPNOBIqESGO+AJmKaQtiBL6OAnuvjicQ4V78p0NzceE8L+pcQvf8PZEvr6unALFjLZN8w4BRPZUx0ifS9E2n3CTHSsJfEHMXXMXfruIpxHpFYC2T7gQKuHPuH3hAuvjoHRh/WDXjC5fp0i3Ob6rl5JI/wCf2NmBlc5Lx/KXm/r6Ml47VcFldbXAO2hJ+R5jafHJm9YpolT02F3XW8LNTaBqJCMg5ZdXK4o7PTGsoIusTDG99cu+tRXL50Z0He8saXXaWAFo6MoSuC2dGwWYNBnEm6giTeOz7E5LVQmK13XG47K4KdFwyoXUQ9LpDO2kHRc/tg1koUjIA=
  gem: proc-buffer
  on:
    repo: LittleStevieBrule/proc-buffer
